### ISSUE TITLE
Cannot start container as of today

### ISSUE THREAD

**Issue by wakeboard143** [ronivay/xen-orchestra-docker#8]
**Error received:**

      error: Script restart attempt #42

      2020-12-12T06:39:10.801Z xo:xo-server ERROR uncaught exception {

      error: Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /etc/xen-orchestra/node_modules/argon2/lib/binding/napi-v3/argon2.node)

            at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)

            at Module.load (internal/modules/cjs/loader.js:863:32)

            at Function.Module._load (internal/modules/cjs/loader.js:708:14)

            at Module.require (internal/modules/cjs/loader.js:887:19)
 
            at require (internal/modules/cjs/helpers.js:74:18)

            at Object.<anonymous> (/etc/xen-orchestra/node_modules/argon2/argon2.js:9:56)

            at Module._compile (internal/modules/cjs/loader.js:999:30)

            at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

            at Module.load (internal/modules/cjs/loader.js:863:32)

            at Function.Module._load (internal/modules/cjs/loader.js:708:14)

            at Module.require (internal/modules/cjs/loader.js:887:19)

            at require (internal/modules/cjs/helpers.js:74:18)

            at Object.<anonymous> (/etc/xen-orchestra/node_modules/hashy/index.js:124:4)

            at Module._compile (internal/modules/cjs/loader.js:999:30)

            at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

            at Module.load (internal/modules/cjs/loader.js:863:32)

            at Function.Module._load (internal/modules/cjs/loader.js:708:14)

            at Module.require (internal/modules/cjs/loader.js:887:19)

            at require (internal/modules/cjs/helpers.js:74:18)

            at Object.<anonymous> (/etc/xen-orchestra/packages/xo-server/src/xo-mixins/subjects.js:4:1)

            at Module._compile (internal/modules/cjs/loader.js:999:30)

            at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

            }

      error: Forever detected script exited with code: 0

**Comment by ronivay** [comment]
Hi,

Thank you. Seems that CentOS 7 (container baseimage) base repo doesn't have new enough libraries. I changed the baseimage to CentOS 8 and new image should be available as soon as dockerhub builds it (maybe an hour or so).

**Comment by wakeboard143** [comment]
Confirmed fixed. Thank you!
